import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Simple from "./components/Navbar";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        
        <Providers>
        <Simple/>
          {children}</Providers>
      </body>
    </html>
  );
}
